name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: git test
      id: git-test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 9
        setup-command: pip install pytest pyyaml
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GIT-TEST_RESULTS: "${{steps.git-test.outputs.result}}"
      with:
        runners: git-test
